[[redirects]]
  from = "/code/learning-moving-targets"
  to = "https://github.com/nikovert/finite-sample-learning-of-moving-targets"
  status = 301
  force = true

[[redirects]]
  from = "/code/distributed-traffic-routing"
  to = "https://github.com/nikovert/distributed_traffic_routing"
  status = 301
  force = true
  
[[redirects]]
  from = "/code/AWE-simulation"
  to = "https://github.com/nikovert/AWE_Simulation"
  status = 301
  force = true

[[redirects]]
  from = "/code"
  to = "https://github.com/nikovert"
  status = 301
  force = true

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
